[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@uniswap/v3-periphery/=node_modules/@uniswap/v3-periphery/",
    "@uniswap/v3-core/=node_modules/@uniswap/v3-core/",
    "@chainlink/contracts/src/=lib/chainlink/contracts/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

solc_version = "0.8.24"
